package app

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/linfree/open-todo/internal/config"
)

// ParsedTask represents structured task data extracted from natural language input.
type ParsedTask struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Priority    string  `json:"priority"`
	DueDate     *string `json:"dueDate"`
	Reminder    *string `json:"reminder"`
}

// BreakdownResult represents a list of subtasks generated by AI.
type BreakdownResult struct {
	Subtasks []Subtask `json:"subtasks"`
}

// Subtask represents a single subtask in a breakdown.
type Subtask struct {
	Title string `json:"title"`
}

// AIService handles AI-powered task operations using OpenAI-compatible APIs.
type AIService struct {
	cfg *config.AIConfig
}

// NewAIService creates a new AIService with configuration loaded from disk.
func NewAIService() *AIService {
	cfg, err := config.LoadAIConfig()
	if err != nil {
		cfg = config.DefaultAIConfig()
	}
	return &AIService{cfg: cfg}
}

// Status returns whether AI is enabled, configured, and the model name.
func (s *AIService) Status() (enabled bool, configured bool, model string) {
	return s.cfg.Enabled, s.cfg.Enabled && s.cfg.APIKey != "", s.cfg.Model
}

// TestConnection tests the AI API connection by sending a minimal chat request.
func (s *AIService) TestConnection() error {
	if s.cfg.APIKey == "" {
		return fmt.Errorf("API密钥未配置")
	}

	type msg struct {
		Role    string `json:"role"`
		Content string `json:"content"`
	}
	body, _ := json.Marshal(map[string]interface{}{
		"model": s.cfg.Model,
		"messages": []msg{
			{Role: "user", Content: "ping"},
		},
		"max_tokens": 1,
	})

	url := strings.TrimRight(s.cfg.BaseURL, "/") + "/chat/completions"
	req, err := http.NewRequest("POST", url, bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("创建请求失败: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+s.cfg.APIKey)

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("网络请求失败: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == 401 || resp.StatusCode == 403 {
		return fmt.Errorf("API密钥无效 (状态码 %d)", resp.StatusCode)
	}
	if resp.StatusCode >= 400 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("API返回错误 (状态码 %d): %s", resp.StatusCode, string(respBody))
	}

	return nil
}

// ParseTask parses natural language input into a structured task using AI.
func (s *AIService) ParseTask(input string) (*ParsedTask, error) {
	if !s.cfg.Enabled || s.cfg.APIKey == "" {
		return nil, fmt.Errorf("AI服务未启用或API密钥未配置")
	}

	systemPrompt := "你是一个任务解析助手。用户会用自然语言描述一个任务，你需要提取出结构化信息，只返回JSON。格式：{\"title\":\"任务标题\",\"description\":\"任务描述\",\"priority\":\"none|low|medium|high\",\"dueDate\":\"ISO8601或null\",\"reminder\":\"ISO8601或null\"}。注意日期要相对当前时间计算，如'明天下午3点'应计算为实际ISO8601时间。"

	now := time.Now()
	contextMsg := fmt.Sprintf("当前时间是 %s（%s）。请根据这个时间计算相对日期。",
		now.Format("2006-01-02T15:04:05-07:00"),
		now.Format("2006年1月2日 15:04"))

	userMsg := contextMsg + "\n用户输入：" + input

	result, err := s.chatCompletion(systemPrompt, userMsg)
	if err != nil {
		return nil, err
	}

	// Extract JSON from the response (may contain markdown code blocks)
	jsonStr := extractJSON(result)

	var parsed ParsedTask
	if err := json.Unmarshal([]byte(jsonStr), &parsed); err != nil {
		return nil, fmt.Errorf("解析AI响应失败: %w, 原始响应: %s", err, result)
	}

	return &parsed, nil
}

// BreakdownTask breaks down a task into subtasks using AI.
func (s *AIService) BreakdownTask(taskTitle, taskDescription string) (*BreakdownResult, error) {
	if !s.cfg.Enabled || s.cfg.APIKey == "" {
		return nil, fmt.Errorf("AI服务未启用或API密钥未配置")
	}

	systemPrompt := "你是一个任务拆解助手。用户会给你一个任务标题和描述，你需要将这个任务拆解为3-5个子任务。只返回JSON。格式：{\"subtasks\":[{\"title\":\"子任务标题\"}]}"

	userMsg := fmt.Sprintf("任务标题：%s\n任务描述：%s", taskTitle, taskDescription)

	result, err := s.chatCompletion(systemPrompt, userMsg)
	if err != nil {
		return nil, err
	}

	// Extract JSON from the response
	jsonStr := extractJSON(result)

	var br BreakdownResult
	if err := json.Unmarshal([]byte(jsonStr), &br); err != nil {
		return nil, fmt.Errorf("解析AI响应失败: %w, 原始响应: %s", err, result)
	}

	return &br, nil
}

// chatCompletion calls the OpenAI-compatible chat completions API.
func (s *AIService) chatCompletion(systemPrompt, userMessage string) (string, error) {
	type Message struct {
		Role    string `json:"role"`
		Content string `json:"content"`
	}

	type RequestBody struct {
		Model    string    `json:"model"`
		Messages []Message `json:"messages"`
	}

	body := RequestBody{
		Model: s.cfg.Model,
		Messages: []Message{
			{Role: "system", Content: systemPrompt},
			{Role: "user", Content: userMessage},
		},
	}

	jsonBody, err := json.Marshal(body)
	if err != nil {
		return "", fmt.Errorf("序列化请求失败: %w", err)
	}

	url := strings.TrimRight(s.cfg.BaseURL, "/") + "/chat/completions"
	req, err := http.NewRequest("POST", url, bytes.NewReader(jsonBody))
	if err != nil {
		return "", fmt.Errorf("创建请求失败: %w", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+s.cfg.APIKey)

	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("API请求失败: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("读取响应失败: %w", err)
	}

	if resp.StatusCode != 200 {
		return "", fmt.Errorf("API返回错误 (状态码 %d): %s", resp.StatusCode, string(respBody))
	}

	var chatResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
		Error *struct {
			Message string `json:"message"`
		} `json:"error"`
	}

	if err := json.Unmarshal(respBody, &chatResp); err != nil {
		return "", fmt.Errorf("解析API响应失败: %w", err)
	}

	if chatResp.Error != nil {
		return "", fmt.Errorf("API错误: %s", chatResp.Error.Message)
	}

	if len(chatResp.Choices) == 0 {
		return "", fmt.Errorf("API返回空响应")
	}

	return chatResp.Choices[0].Message.Content, nil
}

// extractJSON extracts JSON content from a string that may contain markdown code blocks.
func extractJSON(s string) string {
	s = strings.TrimSpace(s)

	// Strip text before the first { or [ (e.g., thinking chain output)
	if idx := strings.Index(s, "{"); idx > 0 {
		s = s[idx:]
	}
	// Also handle the case where JSON is preceded by text and then array
	if idx := strings.Index(s, "["); idx > 0 && (strings.Index(s, "{") == -1 || idx < strings.Index(s, "{")) {
		s = s[idx:]
	}

	// Try to extract from markdown code blocks: ```json ... ```
	if strings.HasPrefix(s, "```") {
		s = strings.TrimPrefix(s, "```json")
		s = strings.TrimPrefix(s, "```")
		if idx := strings.LastIndex(s, "```"); idx >= 0 {
			s = s[:idx]
		}
		return strings.TrimSpace(s)
	}

	// If there's trailing text after the last }, strip it
	if lastBrace := strings.LastIndex(s, "}"); lastBrace >= 0 && lastBrace < len(s)-1 {
		s = s[:lastBrace+1]
	}

	return s
}
